[phases.setup]
nixPkgs = [
    "nodejs", 
    "python311", 
    "python311Packages.pip",
    "python311Packages.requests",
    "python311Packages.python-telegram-bot",
    "python311Packages.python-dotenv",
    "gcc"
]

[phases.install]
cmds = [
    "npm run install:all"
]

[phases.build]
cmds = ["npm run build:frontend"]

[start]
cmd = "npm start"
