[phases.setup]
nixPkgs = ["nodejs", "python311", "gcc", "libGL", "libglvnd"]

[phases.install]
cmds = [
    "npm run install:all",
    "python3 -m pip install -r requirements.txt"
]

[phases.build]
cmds = ["npm run build:frontend"]

[start]
cmd = "npm start"
