services:
  - type: web
    name: smart-priceless-shopper
    env: node
    plan: free
    buildCommand: npm run install:all && npm run build:frontend
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5000
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: WEB_APP_URL
        sync: false
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_PRODUCTION
        value: false
